rackslab/RacksDB

CHANGELOG.md, docs/modules/db/partials/deftypes.adoc, docs/modules/db/partials/objects.adoc, docs/modules/usage/attachments/openapi.yml, racksdb/dtypes/bits.py, schema/racksdb.yml
=> Set bandwidths type to bits instead of bytes

CHANGELOG.md, docs/modules/db/examples/extensions.yml, docs/modules/db/pages/ext.adoc, docs/modules/db/partials/deftypes.adoc, examples/extensions/db/power.yml, examples/extensions/extensions.yml, racksdb/dtypes/watts.py, racksdb/tests/test_defined_type_watts.py
=> Add ~watts defined type

CHANGELOG.md, docs/modules/db/partials/objects.adoc, docs/modules/usage/attachments/openapi.yml, docs/modules/usage/pages/lib.adoc, examples/db/infrastructures/mercury.yml, examples/db/types/misc/kvm.yml, racksdb/bases.py, racksdb/drawers/infrastructure.py, schema/racksdb.yml
=> Add support of miscellaneous equipments

racksdb/web/ui/src/components/HomeViewCards.vue, racksdb/web/ui/src/composables/RacksDBAPI.ts, racksdb/web/ui/src/views/HomeView.vue
=> UI homeview

racksdb/web/ui/package-lock.json, racksdb/web/ui/package.json, racksdb/web/ui/src/components/BreadCrumbs.vue, racksdb/web/ui/src/components/HeaderPage.vue, racksdb/web/ui/src/views/DatacenterDetailsView.vue, racksdb/web/ui/src/views/DatacenterRoomView.vue, racksdb/web/ui/src/views/DatacentersView.vue, racksdb/web/ui/src/views/HomeView.vue, racksdb/web/ui/src/views/InfrastructureDetailsView.vue, racksdb/web/ui/src/views/InfrastructuresView.vue
=> UI breadcrumbs

CHANGELOG.md, docs/modules/usage/attachments/openapi.yml, docs/utils/gen-openapi.py, racksdb/generic/openapi.py, racksdb/web/app.py, racksdb/web/ui/public/config.json, racksdb/web/ui/src/plugins/http.ts, racksdb/web/ui/src/plugins/runtimeConfiguration.ts
This PR introduces versioning in REST API by adding the software version in endpoint paths. Documentation and web UI are updated accordingly.
=> REST API versioning

CHANGELOG.md, docs/modules/install/pages/quickstart.adoc, docs/modules/usage/attachments/openapi.yml, docs/modules/usage/partials/drawing-objects.adoc, pyproject.toml, racksdb/drawers/base.py, racksdb/drawers/infrastructure.py, racksdb/drawers/room.py, schemas/drawings.yml
=> Add support for pixel perfect graphical representations

CHANGELOG.md, docs/modules/usage/partials/drawing-objects.adoc, racksdb/drawers/infrastructure.py, racksdb/drawers/room.py, schemas/drawings.yml
=> Add drawing parameters to control racks and equipment labels

CHANGELOG.md, docs/modules/usage/attachments/openapi.yml, docs/modules/usage/partials/drawing-objects.adoc, racksdb/drawers/base.py, racksdb/drawers/infrastructure.py, schemas/drawings.yml
=> Add possibility to restrict selection of equipment to represent in infrastructure diagrams

CHANGELOG.md, docs/modules/usage/attachments/openapi.yml, docs/modules/usage/partials/drawing-objects.adoc, racksdb/drawers/infrastructure.py, schemas/drawings.yml
=> Add possibility to draw other racks located in the same rows as an infrastructure

CHANGELOG.md, docs/modules/usage/attachments/openapi.yml, docs/modules/usage/pages/racksdb.adoc, pyproject.toml, racksdb/drawers/base.py, racksdb/drawers/coordinates/__init__.py, racksdb/drawers/coordinates/base.py, racksdb/drawers/coordinates/json.py, racksdb/drawers/coordinates/yaml.py, racksdb/drawers/infrastructure.py, racksdb/drawers/room.py, racksdb/exec.py, racksdb/generic/views.py, racksdb/views.py, racksdb/web/app.py
=> Add possibility to generate coordinates file with CLI and REST API

CHANGELOG.md, docs/modules/usage/partials/drawing-deftypes.adoc, racksdb/drawers/base.py, racksdb/drawers/dtypes/hexcolor.py, racksdb/drawers/infrastructure.py, racksdb/drawers/room.py
=> Optional alpha channel on hexcolor defined type

racksdb/drawers/infrastructure.py
Replace some method arguments with more usage of references on other database objects.
=> refactor(draw): replace args by using references

CHANGELOG.md, racksdb/exec.py, racksdb/generic/db.py, racksdb/tests/test_drawer.py, racksdb/web/app.py
This can be useful for other application that use the blueprint to extend their API.
=> Support optional default drawing parameters on web blueprint

CHANGELOG.md, racksdb/web/ui/src/components/DatacenterListInfrastructures.vue, racksdb/web/ui/src/composables/RacksDBAPI.ts, racksdb/web/ui/src/views/DatacenterRoomView.vue
=> UI datacenter room

CHANGELOG.md, docs/modules/db/pages/concepts.adoc, docs/modules/db/partials/objects.adoc, docs/modules/db/partials/prop-types.adoc, docs/modules/db/partials/symbols.adoc, docs/modules/usage/attachments/openapi.yml, docs/modules/usage/pages/lib.adoc, docs/utils/schema-objs.adoc.j2, racksdb/bases.py, racksdb/drawers/infrastructure.py, racksdb/generic/db.py, racksdb/generic/dumpers/json.py, racksdb/generic/dumpers/yaml.py, racksdb/generic/schema.py, schemas/racksdb.yml
=> Add equipment position computed property

CHANGELOG.md, racksdb/web/ui/package-lock.json, racksdb/web/ui/package.json, racksdb/web/ui/src/components/FiltersBar.vue, racksdb/web/ui/src/components/InfrastructureFilters.vue, racksdb/web/ui/src/components/InfrastructureTable.vue
=> UI infrastructure filters

CHANGELOG.md, docs/modules/usage/attachments/openapi.yml, docs/modules/usage/pages/lib.adoc, docs/modules/usage/pages/racksdb.adoc, racksdb/__init__.py, racksdb/bases.py, racksdb/errors.py, racksdb/exec.py, racksdb/generic/openapi.py, racksdb/generic/views.py, racksdb/tests/test_exec.py, racksdb/tests/test_racksdb.py, racksdb/tests/web/test_blueprint.py, racksdb/views.py, racksdb/web/app.py
=> Introduce tags command and REST API endpoint

CHANGELOG.md, racksdb/tests/lib/common.py, racksdb/tests/lib/web.py, racksdb/tests/web/test_app.py, racksdb/tests/web/test_blueprint.py, racksdb/web/app.py
=> Make racksdb-web log error instead of crashing when unable to load db/schema

CHANGELOG.md, racksdb/generic/db.py, racksdb/tests/drawers/test_parameters.py, racksdb/tests/lib/common.py, racksdb/tests/test_racksdb.py
=> Support database files with .yaml extension

CHANGELOG.md, docs/modules/usage/nav.adoc, docs/modules/usage/pages/integrations.adoc
Add Integrations page with ClusterShell integration howto.
fix #92
=> docs: clustershell integration howto

.github/workflows/ci.yml, CHANGELOG.md, docs/modules/usage/attachments/openapi.yml, pyproject.toml, racksdb/generic/openapi.py, racksdb/generic/views.py, racksdb/tests/generic/lib/views.py, racksdb/tests/web/test_app.py, racksdb/tests/web/test_blueprint.py, racksdb/views.py, racksdb/web/app.py
=> Support GET method on REST API draw endpoint

racksdb/tests/lib/reference.py, racksdb/tests/test_exec.py, racksdb/tests/web/test_blueprint.py
Factorize reference testing database validation logic in TestRacksDBReferenceDB common abstract class.
=> tests: refactor web/exec tests

racksdb/tests/lib/common.py
Search testint schema and databases in current working directory, in addition to paths relative to current files. Do not try absolute paths anymore. This approach works in both CI, deb and rpm build environments.
=> tests: search schema/db in cwd
